// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwM5m4xZL9tZg0ZLirjjmJ_RIXNb6_8UU',
    appId: '1:667614492523:web:ba21ef46b2f8bcce357e2e',
    messagingSenderId: '667614492523',
    projectId: 'uasambw-28d7c',
    authDomain: 'uasambw-28d7c.firebaseapp.com',
    storageBucket: 'uasambw-28d7c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgotWAUTozPa4uY-S34yXgZsaBEFwrZfM',
    appId: '1:667614492523:android:eb4a50160c85c478357e2e',
    messagingSenderId: '667614492523',
    projectId: 'uasambw-28d7c',
    storageBucket: 'uasambw-28d7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgQac5XoBkod_k7suKEt0tXBT7SJhNqZs',
    appId: '1:667614492523:ios:3307fe4ef6663e63357e2e',
    messagingSenderId: '667614492523',
    projectId: 'uasambw-28d7c',
    storageBucket: 'uasambw-28d7c.appspot.com',
    iosClientId: '667614492523-sheho443d6smteapgv8tfv8olaqgrv2q.apps.googleusercontent.com',
    iosBundleId: 'com.example.c1419001601',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgQac5XoBkod_k7suKEt0tXBT7SJhNqZs',
    appId: '1:667614492523:ios:3307fe4ef6663e63357e2e',
    messagingSenderId: '667614492523',
    projectId: 'uasambw-28d7c',
    storageBucket: 'uasambw-28d7c.appspot.com',
    iosClientId: '667614492523-sheho443d6smteapgv8tfv8olaqgrv2q.apps.googleusercontent.com',
    iosBundleId: 'com.example.c1419001601',
  );
}
